{% set name = "higra" %}
{% set version = "0.6.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/higra/Higra/archive/refs/tags/{{ version }}.tar.gz
  sha256: 37698e0a363e26880062c126b865ba9ab8f1393f406f4896bbee276ec6d1ee49

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - numpy
  run:
    - python
    - numpy

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - higra

about:
  home: https://github.com/higra/Higra
  license: CeCILL-B
  license_file: LICENSE
  summary: 'Hierarchical graph analysis library'
  doc_url: https://higra.readthedocs.io
  dev_url: https://github.com/higra/Higra

extra:
  recipe-maintainers:
    - imagejan
    - JoOkuma
    - PerretB
